-- Restore legacy app schema compatibility for the current frontend and admin sync tasks.
-- Date: 2026-03-30

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Legacy catalog tables used directly by the current frontend and sync tasks.
-- These objects are intentionally writable because sync-data still upserts into
-- the legacy table names. Read-only compatibility views would not be enough.
-- ---------------------------------------------------------------------------

create table if not exists public.universities (
  id bigint generated by default as identity primary key,
  name text not null,
  code text,
  province text,
  city text,
  level text,
  type text,
  is_985 boolean not null default false,
  is_211 boolean not null default false,
  is_double_first_class boolean not null default false,
  logo_url text,
  founding_year int,
  description text,
  website text,
  tags text[],
  master_dept text,
  campus_area numeric(10, 2),
  student_count int,
  is_private boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.universities add column if not exists name text;
alter table public.universities add column if not exists code text;
alter table public.universities add column if not exists province text;
alter table public.universities add column if not exists city text;
alter table public.universities add column if not exists level text;
alter table public.universities add column if not exists type text;
alter table public.universities add column if not exists is_985 boolean not null default false;
alter table public.universities add column if not exists is_211 boolean not null default false;
alter table public.universities add column if not exists is_double_first_class boolean not null default false;
alter table public.universities add column if not exists logo_url text;
alter table public.universities add column if not exists founding_year int;
alter table public.universities add column if not exists description text;
alter table public.universities add column if not exists website text;
alter table public.universities add column if not exists tags text[];
alter table public.universities add column if not exists master_dept text;
alter table public.universities add column if not exists campus_area numeric(10, 2);
alter table public.universities add column if not exists student_count int;
alter table public.universities add column if not exists is_private boolean not null default false;
alter table public.universities add column if not exists created_at timestamptz default now();
alter table public.universities add column if not exists updated_at timestamptz default now();

create unique index if not exists idx_universities_name_unique on public.universities(name);
create unique index if not exists idx_universities_code_unique on public.universities(code) where code is not null;
create index if not exists idx_universities_province on public.universities(province);
create index if not exists idx_universities_level on public.universities(level);
create index if not exists idx_universities_type on public.universities(type);

create table if not exists public.majors (
  id bigint generated by default as identity primary key,
  university_id bigint,
  code text,
  name text not null,
  category text,
  sub_category text,
  subcategory text,
  degree text,
  duration int,
  description text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.majors add column if not exists name text;
alter table public.majors add column if not exists university_id bigint;
alter table public.majors add column if not exists code text;
alter table public.majors add column if not exists category text;
alter table public.majors add column if not exists sub_category text;
alter table public.majors add column if not exists subcategory text;
alter table public.majors add column if not exists degree text;
alter table public.majors add column if not exists duration int;
alter table public.majors add column if not exists description text;
alter table public.majors add column if not exists created_at timestamptz default now();
alter table public.majors add column if not exists updated_at timestamptz default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'majors_university_id_fkey'
      and conrelid = 'public.majors'::regclass
  ) then
    alter table public.majors
      add constraint majors_university_id_fkey
      foreign key (university_id) references public.universities(id) on delete cascade;
  end if;
end
$$;

create unique index if not exists idx_majors_code_unique on public.majors(code) where code is not null;
create index if not exists idx_majors_university_id on public.majors(university_id);
create index if not exists idx_majors_category on public.majors(category);

create or replace function public.sync_major_subcategory_columns()
returns trigger as $$
begin
  if new.subcategory is null then
    new.subcategory := new.sub_category;
  end if;

  if new.sub_category is null then
    new.sub_category := new.subcategory;
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists majors_sync_subcategory_columns on public.majors;
create trigger majors_sync_subcategory_columns
before insert or update on public.majors
for each row execute procedure public.sync_major_subcategory_columns();

create table if not exists public.admission_scores (
  id bigint generated by default as identity primary key,
  university_id bigint not null,
  major_id bigint,
  province text not null,
  year int not null,
  subject_type text not null,
  batch text not null default 'batch_1',
  min_score int,
  avg_score int,
  min_rank int,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.admission_scores add column if not exists university_id bigint;
alter table public.admission_scores add column if not exists major_id bigint;
alter table public.admission_scores add column if not exists province text;
alter table public.admission_scores add column if not exists year int;
alter table public.admission_scores add column if not exists subject_type text;
alter table public.admission_scores add column if not exists batch text not null default 'batch_1';
alter table public.admission_scores add column if not exists min_score int;
alter table public.admission_scores add column if not exists avg_score int;
alter table public.admission_scores add column if not exists min_rank int;
alter table public.admission_scores add column if not exists created_at timestamptz default now();
alter table public.admission_scores add column if not exists updated_at timestamptz default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'admission_scores_university_id_fkey'
      and conrelid = 'public.admission_scores'::regclass
  ) then
    alter table public.admission_scores
      add constraint admission_scores_university_id_fkey
      foreign key (university_id) references public.universities(id) on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'admission_scores_major_id_fkey'
      and conrelid = 'public.admission_scores'::regclass
  ) then
    alter table public.admission_scores
      add constraint admission_scores_major_id_fkey
      foreign key (major_id) references public.majors(id) on delete set null;
  end if;
end
$$;

create unique index if not exists idx_admission_scores_unique
  on public.admission_scores(university_id, province, year, subject_type, batch);
create index if not exists idx_admission_scores_lookup
  on public.admission_scores(province, subject_type, year, min_score desc);
create index if not exists idx_admission_scores_university
  on public.admission_scores(university_id, year desc);

-- ---------------------------------------------------------------------------
-- Legacy user-owned business tables.
-- ---------------------------------------------------------------------------

create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default '我的方案',
  score int,
  province text,
  subject_type text,
  year int,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.plans add column if not exists user_id uuid;
alter table public.plans add column if not exists name text;
alter table public.plans add column if not exists score int;
alter table public.plans add column if not exists province text;
alter table public.plans add column if not exists subject_type text;
alter table public.plans add column if not exists year int;
alter table public.plans add column if not exists created_at timestamptz default now();
alter table public.plans add column if not exists updated_at timestamptz default now();
create index if not exists idx_plans_user_updated on public.plans(user_id, updated_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'plans_user_id_fkey'
      and conrelid = 'public.plans'::regclass
  ) then
    alter table public.plans
      add constraint plans_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;
end
$$;

create table if not exists public.plan_items (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.plans(id) on delete cascade,
  university_id bigint references public.universities(id) on delete cascade,
  major_id bigint references public.majors(id) on delete set null,
  risk_level text not null default 'unknown',
  sort_order int not null default 0,
  notes text,
  created_at timestamptz default now()
);

alter table public.plan_items add column if not exists plan_id uuid;
alter table public.plan_items add column if not exists university_id bigint;
alter table public.plan_items add column if not exists major_id bigint;
alter table public.plan_items add column if not exists risk_level text not null default 'unknown';
alter table public.plan_items add column if not exists sort_order int not null default 0;
alter table public.plan_items add column if not exists notes text;
alter table public.plan_items add column if not exists created_at timestamptz default now();
create index if not exists idx_plan_items_plan_sort on public.plan_items(plan_id, sort_order asc, created_at asc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'plan_items_plan_id_fkey'
      and conrelid = 'public.plan_items'::regclass
  ) then
    alter table public.plan_items
      add constraint plan_items_plan_id_fkey
      foreign key (plan_id) references public.plans(id) on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'plan_items_university_id_fkey'
      and conrelid = 'public.plan_items'::regclass
  ) then
    alter table public.plan_items
      add constraint plan_items_university_id_fkey
      foreign key (university_id) references public.universities(id) on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'plan_items_major_id_fkey'
      and conrelid = 'public.plan_items'::regclass
  ) then
    alter table public.plan_items
      add constraint plan_items_major_id_fkey
      foreign key (major_id) references public.majors(id) on delete set null;
  end if;
end
$$;

create table if not exists public.favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  university_id bigint references public.universities(id) on delete cascade,
  major_id bigint references public.majors(id) on delete cascade,
  type text not null,
  created_at timestamptz default now()
);

alter table public.favorites add column if not exists user_id uuid;
alter table public.favorites add column if not exists university_id bigint;
alter table public.favorites add column if not exists major_id bigint;
alter table public.favorites add column if not exists type text;
alter table public.favorites add column if not exists created_at timestamptz default now();
create index if not exists idx_favorites_user_created on public.favorites(user_id, created_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'favorites_user_id_fkey'
      and conrelid = 'public.favorites'::regclass
  ) then
    alter table public.favorites
      add constraint favorites_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'favorites_university_id_fkey'
      and conrelid = 'public.favorites'::regclass
  ) then
    alter table public.favorites
      add constraint favorites_university_id_fkey
      foreign key (university_id) references public.universities(id) on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'favorites_major_id_fkey'
      and conrelid = 'public.favorites'::regclass
  ) then
    alter table public.favorites
      add constraint favorites_major_id_fkey
      foreign key (major_id) references public.majors(id) on delete cascade;
  end if;
end
$$;

create table if not exists public.data_sync_logs (
  id uuid primary key default gen_random_uuid(),
  task_type text not null,
  status text not null,
  executed_by text,
  message text,
  records_added int not null default 0,
  finished_at timestamptz,
  created_at timestamptz default now()
);

alter table public.data_sync_logs add column if not exists task_type text;
alter table public.data_sync_logs add column if not exists status text;
alter table public.data_sync_logs add column if not exists executed_by text;
alter table public.data_sync_logs add column if not exists message text;
alter table public.data_sync_logs add column if not exists records_added int not null default 0;
alter table public.data_sync_logs add column if not exists finished_at timestamptz;
alter table public.data_sync_logs add column if not exists created_at timestamptz default now();
create index if not exists idx_data_sync_logs_created on public.data_sync_logs(created_at desc);
create index if not exists idx_data_sync_logs_task_status on public.data_sync_logs(task_type, status);

-- ---------------------------------------------------------------------------
-- RLS policies.
-- ---------------------------------------------------------------------------

alter table public.universities enable row level security;
alter table public.majors enable row level security;
alter table public.admission_scores enable row level security;
alter table public.plans enable row level security;
alter table public.plan_items enable row level security;
alter table public.favorites enable row level security;
alter table public.data_sync_logs enable row level security;

drop policy if exists "universities_select_public" on public.universities;
create policy "universities_select_public"
on public.universities for select
using (true);

drop policy if exists "majors_select_public" on public.majors;
create policy "majors_select_public"
on public.majors for select
using (true);

drop policy if exists "admission_scores_select_public" on public.admission_scores;
create policy "admission_scores_select_public"
on public.admission_scores for select
using (true);

drop policy if exists "plans_select_own" on public.plans;
create policy "plans_select_own"
on public.plans for select
using (auth.uid() = user_id);

drop policy if exists "plans_insert_own" on public.plans;
create policy "plans_insert_own"
on public.plans for insert
with check (auth.uid() = user_id);

drop policy if exists "plans_update_own" on public.plans;
create policy "plans_update_own"
on public.plans for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "plans_delete_own" on public.plans;
create policy "plans_delete_own"
on public.plans for delete
using (auth.uid() = user_id);

drop policy if exists "plan_items_select_own" on public.plan_items;
create policy "plan_items_select_own"
on public.plan_items for select
using (
  exists (
    select 1
    from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = auth.uid()
  )
);

drop policy if exists "plan_items_insert_own" on public.plan_items;
create policy "plan_items_insert_own"
on public.plan_items for insert
with check (
  exists (
    select 1
    from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = auth.uid()
  )
);

drop policy if exists "plan_items_update_own" on public.plan_items;
create policy "plan_items_update_own"
on public.plan_items for update
using (
  exists (
    select 1
    from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = auth.uid()
  )
);

drop policy if exists "plan_items_delete_own" on public.plan_items;
create policy "plan_items_delete_own"
on public.plan_items for delete
using (
  exists (
    select 1
    from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = auth.uid()
  )
);

drop policy if exists "favorites_select_own" on public.favorites;
create policy "favorites_select_own"
on public.favorites for select
using (auth.uid() = user_id);

drop policy if exists "favorites_insert_own" on public.favorites;
create policy "favorites_insert_own"
on public.favorites for insert
with check (auth.uid() = user_id);

drop policy if exists "favorites_delete_own" on public.favorites;
create policy "favorites_delete_own"
on public.favorites for delete
using (auth.uid() = user_id);

drop policy if exists "data_sync_logs_select_admin" on public.data_sync_logs;
create policy "data_sync_logs_select_admin"
on public.data_sync_logs for select
using (
  exists (
    select 1
    from public.user_profiles up
    where up.id = auth.uid()
      and up.role = 'admin'
  )
);

grant select on public.universities, public.majors, public.admission_scores to anon, authenticated;
grant select, insert, update, delete on public.plans, public.plan_items, public.favorites to authenticated;
grant select on public.data_sync_logs to authenticated;

-- ---------------------------------------------------------------------------
-- Legacy analytics RPCs used directly by the current frontend.
-- ---------------------------------------------------------------------------

create or replace function public.get_university_stats()
returns jsonb
language sql
stable
as $$
  with type_stats as (
    select type as key, count(*)::int as value
    from public.universities
    where coalesce(type, '') <> ''
    group by type
  ),
  level_stats as (
    select '985'::text as key, count(*)::int as value
    from public.universities
    where is_985
    union all
    select '211'::text as key, count(*)::int as value
    from public.universities
    where not is_985 and is_211
    union all
    select '双一流'::text as key, count(*)::int as value
    from public.universities
    where not is_985 and not is_211 and is_double_first_class
    union all
    select '普通本科'::text as key, count(*)::int as value
    from public.universities
    where not is_985 and not is_211 and not is_double_first_class
  ),
  province_stats as (
    select province as key, count(*)::int as value
    from public.universities
    where coalesce(province, '') <> ''
    group by province
  )
  select jsonb_build_object(
    'total', (select count(*)::int from public.universities),
    'byType', coalesce((select jsonb_object_agg(key, value) from type_stats), '{}'::jsonb),
    'byLevel', coalesce((select jsonb_object_agg(key, value) from level_stats), '{}'::jsonb),
    'by985', coalesce((select count(*)::int from public.universities where is_985), 0),
    'byProvince', coalesce((select jsonb_object_agg(key, value) from province_stats), '{}'::jsonb)
  );
$$;

create or replace function public.get_score_stats(p_province text default null)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select *
    from public.admission_scores
    where p_province is null or province = p_province
  ),
  bucketed as (
    select
      case
        when min_score is null then '未知'
        when min_score < 400 then '400以下'
        when min_score < 450 then '400-449'
        when min_score < 500 then '450-499'
        when min_score < 550 then '500-549'
        when min_score < 600 then '550-599'
        else '600及以上'
      end as bucket
    from filtered
  ),
  distribution as (
    select bucket as key, count(*)::int as value
    from bucketed
    group by bucket
  ),
  year_trend as (
    select
      year,
      round(avg(min_score)::numeric, 2) as avg_min_score
    from filtered
    where year is not null
      and min_score is not null
    group by year
    order by year
  )
  select jsonb_build_object(
    'distribution', coalesce((select jsonb_object_agg(key, value) from distribution), '{}'::jsonb),
    'yearTrend', coalesce((
      select jsonb_agg(
        jsonb_build_object('year', year, 'avgMinScore', avg_min_score)
        order by year
      )
      from year_trend
    ), '[]'::jsonb),
    'totalRecords', (select count(*)::int from filtered)
  );
$$;

create or replace function public.get_major_stats()
returns jsonb
language sql
stable
as $$
  with category_stats as (
    select category as key, count(*)::int as value
    from public.majors
    where coalesce(category, '') <> ''
    group by category
  )
  select jsonb_build_object(
    'total', (select count(*)::int from public.majors),
    'byCategory', coalesce((select jsonb_object_agg(key, value) from category_stats), '{}'::jsonb)
  );
$$;

create or replace function public.get_distinct_major_categories()
returns table(category text)
language sql
stable
as $$
  select distinct m.category
  from public.majors m
  where coalesce(m.category, '') <> ''
  order by m.category;
$$;

grant execute on function public.get_university_stats() to anon, authenticated;
grant execute on function public.get_score_stats(text) to anon, authenticated;
grant execute on function public.get_major_stats() to anon, authenticated;
grant execute on function public.get_distinct_major_categories() to anon, authenticated;
